// frontend/svelte_poc/src/App.svelte
<script>
  import { Router, Route } from 'svelte-routing';
  import Navbar from './components/Navbar.svelte';
  import Dashboard from './views/Dashboard.svelte';
  import ArtefactPage from './views/ArtefactPage.svelte';
  import TestResultsSearchPage from './views/TestResultsSearchPage.svelte';
  import IssuesPage from './views/IssuesPage.svelte';
  import IssuePage from './views/IssuePage.svelte';

  export let url = '';
</script>

<div id="app">
  <Router {url} basepath="/svelte_poc">
    <Navbar />
    <main>
      <div class="content-container">
        <Route path="/" component={()=> Dashboard} family="snap" />
        <Route path="/snaps" let:params>
          <Dashboard family="snap" />
        </Route>
        <Route path="/snaps/:artefactId" component={ArtefactPage} />
        <Route path="/debs" let:params>
          <Dashboard family="deb" />
        </Route>
        <Route path="/debs/:artefactId" component={ArtefactPage} />
        <Route path="/charms" let:params>
          <Dashboard family="charm" />
        </Route>
        <Route path="/charms/:artefactId" component={ArtefactPage} />
        <Route path="/images" let:params>
          <Dashboard family="image" />
        </Route>
        <Route path="/images/:artefactId" component={ArtefactPage} />
        <Route path="/test-results" component={TestResultsSearchPage} />
        <Route path="/issues" component={IssuesPage} />
        <Route path="/issues/:issueId" component={IssuePage} />
      </div>
    </main>
  </Router>
</div>

<style>
  :global(*) {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }

  :global(body) {
    font-family: Ubuntu, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Cantarell, sans-serif;
    line-height: 1.6;
    color: #111;
    background: #fff;
  }

  #app {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
  }

  main {
    flex: 1;
    display: flex;
    justify-content: center;
  }

  .content-container {
    width: 100%;
    max-width: 1780px;
    padding: 0 24px;
  }
</style>

// frontend/react_poc/src/App.jsx
import { BrowserRouter as Router, Routes, Route, Navigate } from 'react-router-dom'
import Navbar from './components/Navbar'
import Dashboard from './views/Dashboard'
import ArtefactPage from './views/ArtefactPage'
import TestResultsSearchPage from './views/TestResultsSearchPage'
import IssuesPage from './views/IssuesPage'
import IssuePage from './views/IssuePage'
import './App.css'

export default function App() {
  return (
    <Router basename="/react_poc">
      <div id="app">
        <Navbar />
        <main>
          <div className="content-container">
            <Routes>
              <Route path="/" element={<Navigate to="/snaps" replace />} />
              <Route path="/snaps" element={<Dashboard />} />
              <Route path="/snaps/:artefactId" element={<ArtefactPage />} />
              <Route path="/debs" element={<Dashboard />} />
              <Route path="/debs/:artefactId" element={<ArtefactPage />} />
              <Route path="/charms" element={<Dashboard />} />
              <Route path="/charms/:artefactId" element={<ArtefactPage />} />
              <Route path="/images" element={<Dashboard />} />
              <Route path="/images/:artefactId" element={<ArtefactPage />} />
              <Route path="/test-results" element={<TestResultsSearchPage />} />
              <Route path="/issues" element={<IssuesPage />} />
              <Route path="/issues/:issueId" element={<IssuePage />} />
            </Routes>
          </div>
        </main>
      </div>
    </Router>
  )
}
