// frontend/svelte_poc/src/lib/components/Navbar.svelte
<script lang="ts">
  import { page } from '$app/state';
  import { base } from '$app/paths';
  import NavbarEntry from './navbar/NavbarEntry.svelte';
  import NavbarDropdown from './navbar/NavbarDropdown.svelte';
  import { configuredTabs, helpLinks } from '$lib/config';
  import { userStore } from '$lib/stores/user.svelte';
  import { notificationsStore } from '$lib/stores/notifications.svelte';

  const pathname = $derived(page.url.pathname);

  $effect(() => {
    if (userStore.isLoggedIn) {
      notificationsStore.loadUnreadCount();
    }
  });

  const badgeText = $derived(
    notificationsStore.unreadCount > 99 ? '99+' : String(notificationsStore.unreadCount),
  );

  function loginUrl(): string {
    return `/v1/auth/saml/login?return_to=${encodeURIComponent(window.location.href)}`;
  }

  function logoutUrl(): string {
    return `/v1/auth/saml/logout?return_to=${encodeURIComponent(window.location.href)}`;
  }
</script>

<nav class="navbar" aria-label="Main navigation">
  <div class="navbar-inner">
    <a href="{base}/" class="logo">
      <img src="{base}/logo.png" alt="Test Observer" onerror={(e) => { (e.currentTarget as HTMLImageElement).style.display = 'none'; }} />
    </a>

    {#each configuredTabs as tab}
      <NavbarEntry href={tab.href} title={tab.label} isActive={pathname.startsWith(tab.href)} />
    {/each}

    <div class="spacer"></div>

    <NavbarEntry href="{base}/test-results" title="Search" isActive={pathname.startsWith(`${base}/test-results`)} />
    <NavbarEntry href="{base}/issues" title="Issues" isActive={pathname.startsWith(`${base}/issues`)} />

    <NavbarDropdown label="Help">
      {#each helpLinks as link}
        <a href={link.href} target="_blank" rel="noopener noreferrer">{link.label}</a>
      {/each}
    </NavbarDropdown>

    {#if userStore.isLoggedIn}
      <a href="{base}/notifications" class="bell-link" aria-label="Notifications">
        <span class="bell-icon">🔔</span>
        {#if notificationsStore.unreadCount > 0}
          <span class="bell-badge">{badgeText}</span>
        {/if}
      </a>
    {/if}

    {#if userStore.isLoggedIn}
      <NavbarDropdown label={userStore.current?.name ?? ''}>
        <a href={logoutUrl()}>Log out</a>
      </NavbarDropdown>
    {:else}
      <a href={loginUrl()} class="nav-button">Log in</a>
    {/if}
  </div>
</nav>

<style>
  .navbar {
    height: 57px;
    background: #333;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
  }

  .navbar-inner {
    display: flex;
    align-items: center;
    max-width: 1800px;
    width: 100%;
    padding: 0 32px;
    height: 100%;
  }

  .logo {
    display: flex;
    align-items: center;
    margin-right: 16px;
    height: 100%;
  }

  .logo img {
    height: 57px;
    width: auto;
  }

  .spacer {
    flex: 1;
  }

  .nav-button {
    display: flex;
    align-items: center;
    height: 100%;
    padding: 0 16px;
    color: white;
    font-size: 0.95rem;
    font-weight: 500;
  }

  .nav-button:hover {
    background: hsl(0 0% 28%);
  }

  .bell-link {
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100%;
    padding: 0 12px;
    text-decoration: none;
  }

  .bell-link:hover {
    background: hsl(0 0% 28%);
  }

  .bell-icon {
    font-size: 1.25rem;
    line-height: 1;
  }

  .bell-badge {
    position: absolute;
    top: 10px;
    right: 4px;
    background: #c7162b;
    color: #fff;
    font-size: 0.65rem;
    font-weight: 700;
    min-width: 16px;
    height: 16px;
    line-height: 16px;
    text-align: center;
    border-radius: 8px;
    padding: 0 4px;
    pointer-events: none;
  }
</style>

// frontend/vue_poc/src/components/Navbar.vue
<template>
  <nav class="navbar">
    <div class="navbar-content">
      <div class="navbar-logo">
        <img src="/canonical.png" alt="Canonical" />
      </div>
      
      <div class="navbar-links">
        <router-link to="/snaps" class="nav-link">Snap Testing</router-link>
        <router-link to="/debs" class="nav-link">Deb Testing</router-link>
        <router-link to="/charms" class="nav-link">Charm Testing</router-link>
        <router-link to="/images" class="nav-link">Image Testing</router-link>
        
        <div class="spacer"></div>
        
        <router-link to="/test-results" class="nav-link">Search</router-link>
        <router-link to="/issues" class="nav-link">Issues</router-link>
        
        <div class="dropdown">
          <button class="nav-button dropdown-toggle">Help</button>
          <div class="dropdown-menu">
            <a href="https://canonical-test-observer.readthedocs-hosted.com/en/latest/" target="_blank" class="dropdown-item">Docs</a>
            <a href="https://github.com/canonical/test_observer/issues" target="_blank" class="dropdown-item">Feedback</a>
            <a href="https://github.com/canonical/test_observer" target="_blank" class="dropdown-item">Source Code</a>
          </div>
        </div>
        
        <div v-if="user" class="dropdown">
          <button class="nav-button dropdown-toggle">{{ user.name }}</button>
          <div class="dropdown-menu">
            <a :href="logoutUrl" class="dropdown-item">Log out</a>
          </div>
        </div>
        <button v-else @click="login" class="nav-button">Log in</button>
      </div>
    </div>
  </nav>
</template>

<script>
export default {
  name: 'Navbar',
  data() {
    return {
      user: null
    }
  },
  computed: {
    apiUrl() {
      // In production, this would come from environment config
      return window.location.origin.replace(':30001', ':30000')
    },
    logoutUrl() {
      return `${this.apiUrl}/v1/auth/saml/logout?return_to=${encodeURIComponent(window.location.origin)}`
    }
  },
  methods: {
    login() {
      const loginUrl = `${this.apiUrl}/v1/auth/saml/login?return_to=${encodeURIComponent(window.location.origin)}`
      window.location.href = loginUrl
    }
  }
}
</script>

<style scoped>
.navbar {
  background: #772953;
  height: 57px;
  display: flex;
  justify-content: center;
}

.navbar-content {
  width: 100%;
  max-width: 1200px;
  padding: 0 24px;
  display: flex;
  align-items: center;
  gap: 16px;
}

.navbar-logo img {
  height: 24px;
  filter: brightness(0) invert(1);
}

.navbar-links {
  flex: 1;
  display: flex;
  align-items: center;
  gap: 0;
}

.nav-link,
.nav-button {
  color: white;
  text-decoration: none;
  padding: 16px;
  font-size: 16px;
  font-weight: 400;
  background: none;
  border: none;
  cursor: pointer;
  height: 57px;
  display: flex;
  align-items: center;
  white-space: nowrap;
  transition: background-color 0.2s;
}

.nav-link:hover,
.nav-button:hover {
  background-color: rgba(255, 255, 255, 0.1);
}

.nav-link.router-link-active {
  background-color: #E95420;
}

.spacer {
  flex: 1;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-toggle::after {
  content: ' ▾';
  font-size: 12px;
}

.dropdown-menu {
  display: none;
  position: absolute;
  top: 100%;
  left: 0;
  background: #772953;
  min-width: 160px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
  z-index: 1000;
}

.dropdown:hover .dropdown-menu {
  display: block;
}

.dropdown-item {
  color: white;
  text-decoration: none;
  padding: 16px;
  display: block;
  font-size: 16px;
  transition: background-color 0.2s;
}

.dropdown-item:hover {
  background-color: rgba(255, 255, 255, 0.1);
}
</style>
